easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Movie
       - App\Entity\Serie
       - App\Entity\Season
       - App\Entity\Episode
       - App\Entity\User
